### ISSUE TITLE
Still live?

### ISSUE THREAD

**Issue by Kaczuc** [grisha/mod_python#112]
is the project still supported?

**Comment by grisha** [comment]
Yes, by people like you :)

**Comment by Kaczuc** [comment]
I have one question, so can I import any module into my page project from python packages? Am I limited only and exclusively to django modules? 
And if there is a possibility of more introduction for new people to python use this apache2 interfacing mod, we are talking about typical examples that we can find for php, for example, connecting to the database and displaying data from it or entering data from a form, etc.

**Comment by grisha** [comment]
mod_python has nothing to do with django, though IIRC django can use mod_python. All your questions are probably answered in the documentation: http://modpython.org/live/current/doc-html/contents.html
