### ISSUE TITLE
detect python version failed

### ISSUE THREAD

**Issue by hbfl** [grisha/mod_python#116]
Please  change in 'configure.in'  the syntax to detect the python 'major.minor' version
in line 170

[.. is
 -  PyVERSION=`$PYTHON_BIN -c ['import sys; print('{}.{}'.format(*sys.version_info))'`]

[ ..to 
+  PyVERSION=`$PYTHON_BIN -c ['import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))'`]

thanks
Holger

**Comment by grisha** [comment]
For documentation/posterity - could you describe what the issue is with the current version of this line?

**Comment by hbfl** [comment]
oh, sorry, I forgot

with 3.10

checking for Apache include directory... -I/usr/include/apache2
checking for --with-python... python3.10
checking Python version...   File "<string>", line 1
    import sys; print({}.{}.format(*sys.version_info))
                         ^
SyntaxError: invalid syntax

---patched

checking for Apache libexec directory... /usr/lib/apache2/modules
checking for Apache include directory... -I/usr/include/apache2
checking for --with-python... python3.10
checking Python version... 3.10

--------------------

with 3.8

checking for Apache include directory... -I/usr/include/apache2
checking for --with-python... python3.8
checking Python version...   File "<string>", line 1
    import sys; print({}.{}.format(*sys.version_info))
                         ^
SyntaxError: invalid syntax

---- patched

checking for Apache libexec directory... /usr/lib/apache2/modules
checking for Apache include directory... -I/usr/include/apache2
checking for --with-python... python3.8
checking Python version... 3.8
checking for --with-mutex-dir... no

--------
grr, I forgot also the ` `   

PyVERSION=`$PYTHON_BIN -c ['import sys; print('{}.{}'.format(*sys.version_info))'`]

PyVERSION=`$PYTHON_BIN -c ['import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))'`]
