### ISSUE TITLE
How to configure the Python interpreter path?

### ISSUE THREAD

**Issue by t2wu** [grisha/mod_python#119]
I'm trying to get some old code to work. I am using Apache/2.4.54 (in a PHP docker image: php:8.0-apache, Debian based).

The code was written in Python 2 but the image comes with Python 3. So I used Anaconda get get a Python 2.7 installed. Apache keep on calling Python 3 on the system. How do I get it to use the right path? I tried to configure the $PATH env variable inside `/etc/apache2/envvars` but it's not working.

**Comment by grisha** [comment]
The LD_LIBRARY_PATH env var controls where libraries are loaded from. Not sure it will solve your problem, but it's something to try.

**Comment by t2wu** [comment]
I still can't get it to work yet. Isn't LD_LIBRARY_PATH for binary's runtime linker?

The problem I have right now is that there are multiple Python executable on the system. It seems to be using `/usr/bin/python3`. I want it to use `/usr/local/miniconda/bin/python`.

How does Apache decide which Python executable to use? And strangely enough even after I log into the container and manually removed /usr/bin/python3 from the docker image it still is executing Python 3.

**Comment by grisha** [comment]
mod_python doesn't use your Python executable, it tries to load libpython.so into the Apache process. You can find out where the lib is with something like:
```
from distutils import sysconfig;
print(sysconfig.get_config_var("LIBDIR"))
```
But if mod_python was compiled for Python 2 it can't just load the Python3 lib or vice versa without recompilation.

**Comment by t2wu** [comment]
OK thank you very much. I got it to work.
