### ISSUE TITLE
Python 3.12 failed because imp was removed.

### ISSUE THREAD

**Issue by dviererbe** [grisha/mod_python#130]
Running the `libapache2-mod-python` package with Python 3.12 failed.

This is caused by the missing library `imp` in Python 3.12.

The Python library imp is marked as deprecated since Python 3.4 and was removed in Python 3.12. The documentation recommends replacing it with `importlib`. See https://docs.python.org/3.11/library/imp.html

See downstream bug report for further information: https://bugs.launchpad.net/ubuntu/+source/libapache2-mod-python/+bug/2054133

**Comment by dviererbe** [comment]
I already have a patch, but I am not confident that this is a 100% replacement due to my lacking understanding of `libapache2-mod-python`, `imp` and `importlib`. Therefore, feedback would be greatly appreciated.

```patch
--- a/lib/python/mod_python/publisher.py
+++ b/lib/python/mod_python/publisher.py
@@ -34,7 +34,7 @@
 import sys
 import os
 from os.path import exists, isabs, normpath, split, isfile, join, dirname
-import imp
+import importlib.machinery
 import re
 import base64
 
@@ -43,7 +43,7 @@
 import collections
 
 
-imp_suffixes = " ".join([x[0][1:] for x in imp.get_suffixes()])
+imp_suffixes = " ".join(x[1:] for x in importlib.machinery.all_suffixes())
 
 # Python 2/3 compat workaround
 PY2 = sys.version[0] == '2'
--- a/lib/python/mod_python/cgihandler.py
+++ b/lib/python/mod_python/cgihandler.py
@@ -18,7 +18,7 @@
  #
 
 from . import apache
-import imp
+import importlib.util
 import os
 import sys
 
@@ -88,21 +88,22 @@
 
             try:
                 # we do not search the pythonpath (security reasons)
-                fd, path, desc = imp.find_module(module_name, [dir])
-            except ImportError:
+                spec = importlib.util.find_spec(module_name, dir)
+            except (ModuleNotFoundError, ValueError):
                 raise apache.SERVER_RETURN(apache.HTTP_NOT_FOUND)
 
-            # this executes the module
-            imp.load_module(module_name, fd, path, desc)
+            if spec is None:
+                raise apache.SERVER_RETURN(apache.HTTP_NOT_FOUND)
+
+            module = importlib.util.module_from_spec(spec)
+            sys.modules[module_name] = module
+            spec.loader.exec_module(module)
 
             return apache.OK
 
         finally:
             # unsimulate the cgi environment
             apache.restore_nocgi(env, si, so)
-            try:
-                fd.close()
-            except: pass
             os.chdir(cwd)
     finally:
         _lock.release()

```

**Comment by grisha** [comment]
Thanks for the patch, @dviererbe! I'm not currently set up to test this, it looks good to me, but I also remember stuff related to `imp` being rather finicky, so if someone could chime in it would be super helpful.

**Comment by grisha** [comment]
@dviererbe I pushed your patch unto a branch so that it's easier for people to test, it's a commit authored as you (hope that's okay): d07ce78. We can let it sit there for a while for people to test and then we can merge if no problems are found.

**Comment by dviererbe** [comment]
That is fine with me, Thanks!

FYI: I will request a upload of this patch in Ubuntu 24.04 LTS (Noble Numbat). I need to get this fixed so we can finish the Python 3.12 transition.

**Comment by panlinux** [comment]
Here is an `imp` to `importlib` migration guide: https://docs.python.org/3/whatsnew/3.12.html#imp

**Comment by panlinux** [comment]
> @panlinux I used this or a similar migration guide. The challenge was that most use cases do not want to load the module from a specific directory, like this piece of code.

Indeed, it still seems to be loading the module from anywhere in pythonpath. Could you please verify my results? I'm not 100% confident I configured things correctly.

**Comment by grisha** [comment]
> And I'm finding this way to use mod_python odd: why even use mod_python in the CGI case?

@panlinux odd indeed, but it somehow made sense in the 90's. 

The `imp.find_moduel()` took an argument, the directory name, and it looks like `find_spec()` does too - IIRC this was what prevented arbitrary modules from being imported. There's even a comment about that: https://github.com/grisha/mod_python/blob/master/lib/python/mod_python/cgihandler.py#L90-L91

With the specific case of the `os` module, I'm wondering whether the `imp` version did that too, so maybe there is no problem, not sure.

I'd be curious what happens if you try a module that isn't presumably already imported, something other than `os` and more obscure but in the standard lib,  e.g. `base64` or something.

**Comment by panlinux** [comment]
I tried this, and that loaded the specific `os.py` script I had:
```
                spec = importlib.util.spec_from_file_location(module_name, req.subprocess_env["script_filename"])
```

**Comment by panlinux** [comment]
> The `imp.find_moduel()` took an argument, the directory name, and it looks like `find_spec()` does too - IIRC this was what prevented arbitrary modules from being imported. There's even a comment about that: https://github.com/grisha/mod_python/blob/master/lib/python/mod_python/cgihandler.py#L90-L91

`find_spec()` takes `name, package=None`, not a path.

**Comment by panlinux** [comment]
> I'd be curious what happens if you try a module that isn't presumably already imported, something other than `os` and more obscure but in the standard lib, e.g. `base64` or something.

Interesting, both http://10.0.102.65/cgi-python/base64 and http://10.0.102.65/cgi-python/base64.py actually loaded the `base64.py` script I had in the directory.

**Comment by grisha** [comment]
> I tried this, and that loaded the specific `os.py` script I had:
> 
> ```
> spec = importlib.util.spec_from_file_location(module_name, req.subprocess_env["script_filename"])
> ```

So this ^ looks like the winner? With a small pick on the `req.subprocess_env["script_filename"]` part, I think should be:

```python
 spec = importlib.util.spec_from_file_location(module_name, os.path.join(dir, file))
```

because looking at line 69 it's apparently possible that `req.subprocess_env["script_filename"]` might not exist in which case it falls back to `req.filename`.
