### ISSUE TITLE
sys.version provided by mod_python cannot be parsed by python's standard platform module

### ISSUE THREAD

**Issue by msquire** [grisha/mod_python#138]
Distribution: Ubuntu 24.04.1 (noble)
python version: 3.12.3
mod_python version: 3.5.0.1
apache2 version: 2.4.58

The result of `python3 -c 'import sys; print(sys.version)'` is:

`3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]`

More generically "X.Y.Z (buildno, builddate, buildtime) [compiler]" and this format is required by the `platform._sys_version()` function which is used by (for example) `platform.python_version()` to extract the "X.Y.Z" part. If sys.version is not in this format it raises ValueError.

The problem is that mod_python seems to set sys.version to be only the "X.Y.Z" part which means the error gets raised. I encountered this problem with Trac 1.6, but some research done by someone else at Ubuntu's launchpad.net suggests this might be causing issues with other projects too.

I created a minimal test case which illustrates the problem (attached). In case you're wondering, 2078527 is the number of the [downstream bug report](https://bugs.launchpad.net/ubuntu/+source/libapache2-mod-python/+bug/2078527) I filed with Ubuntu. To install it (might be slightly different on a platform other than Ubuntu):

1. Extract the attached archive `python_bug_2078527.tar.gz` into `/opt/local/tmp` (you can put it somewhere else, but you'll need to edit the `PythonPath` directive in the supplied `apache2.conf` file if you do).
2. Add `Include /opt/local/tmp/python_bug_2078527/apache2.conf` to the bottom of the VirtualHost definition in `/etc/apache2/sites-available/000-default.conf` (assuming the default location of this configuration file).
3. Run `systemctl restart apache2` (or `apache2ctl restart` if it's not a systemd platform).

Now go to http://localhost/mod-python-bug-2078527 in a browser. You should see this:

```
Python sys.version              3.12.3
platform.python_version()       ValueError: failed to parse CPython sys.version: '3.12.3'
```

If you go to http://localhost/mod-python-bug-2078527?hack_fix=1 you should see this:

```
Python sys.version              3.12.3 (dummy, dummy, dummy) [dummy]
platform.python_version()       3.12.3
```

[python_bug_2078527.tar.gz](https://github.com/user-attachments/files/16881153/python_bug_2078527.tar.gz)

**Comment by grisha** [comment]
@msquire mod_python latest is `3.5.0.3` and I do remember there being some version-related stuff being fixed, not 100% sure, but there is a chance that the issue you're describing is already solved.

**Comment by msquire** [comment]
Thank you for your quick response! Unfortunately the problem is not solved in the latest version.

I tried compiling and installing 3.5.0.3 from source but alas the problem still exists. The same is true with master.

**Comment by grisha** [comment]
Looks like this bug was introduced in 2006  in this commit 65df799, fix coming up!

**Comment by grisha** [comment]
I just tagged 3.5.0.4 - should have this issue addressed.

**Comment by msquire** [comment]
I was curious how this bug could have existed for so long without anyone noticing. It seems it predates even 2006 but just hasn't manifested itself thus far because prior to v3.12.0 of cpython the Py_GetVersion() function reinitialised the static buffer that contains the version string every time it was called. So, even though strtok was effectively truncating it by inserting a NULL byte after the first part of the version, it was getting reset the next time the function was called. Starting with v3.12.0 the Py_GetVersion() function only initialises the buffer once the first time it is called.

Anyway, thanks again for fixing it :)

**Comment by grisha** [comment]
> prior to v3.12.0 of cpython the Py_GetVersion() function reinitialised the static buffer

was wondering that myself - thanks for digging this up @msquire !
