### ISSUE TITLE
GIT required when installing from the tarball

### ISSUE THREAD

**Issue by jcea** [grisha/mod_python#20]
Version is calculated incorrectly, installed version will mismatch and you get stuff like this:

"""
/usr/local/lib/python3.3/site-packages/mod_python-fatal_.Not.a.git.repository._or.any.parent.up.to.mount.point._tmp_Stopping.at.filesystem.boundary._GIT_DISCOVERY_ACROSS_FILESYSTEM.not.set_._3.5.0_-py3.3.egg-info
"""

**Comment by opoplawski** [comment]
It would be nice to have this fix in a released version.
