### ISSUE TITLE
mod_python.so: undefined symbol: sincos Action 'configtest' failed.

### ISSUE THREAD

**Issue by fneitzel** [grisha/mod_python#40]
I wanted to have a working python3 with Apache. 
But I don't get it working. What am I doing wrong?

Platform: Linux-3.2.0-4-amd64 Debian-7.8 (3.2.65)
Apache-Version: 2.2.22
Python-Version: 3.5.0a2
mod_python version : 3.5.0-9d223c3

Compiled Python3.5 with CFLAGSFORSHARED="-fPIC" CCSHARED="-fPIC" CCSHARED="-fPIC"
Compiled mod_python from git-Source with: ./configure --with-apxs=/usr/bin/apxs2 --with-python=/usr/local/bin/python3.5 --with-mutex-dir=/tmp --with-max-locks=32

Apache has no errorlogs concerning the issue.
When testing with 'make test':

apache2: Syntax error on line 48 of /root/Downloads/mod_python/test/conf/test.conf: Cannot load /root/Downloads/mod_python/src/mod_python.so into server: /root/Downloads/mod_python/src/mod_python.so: undefined symbol: sincos
  Stopping Apache...

...over and over again.

By installing from package: apt-get install libapache2-mod-python everything works, beacuse apache is using python2.7. But this is not what i wanted ...

How to tell Apache that he's not allowed to use Python 2.7 instead Python3.5 has to be used!
I red that the compiled mod_python is deciding which Python is used ... but how can i tell the packet manager that 'libapache2-mod-python' shall be installed for 3.5

EDIT: So this is the current install :-1: 
[Sun Mar 29 20:36:21 2015] [notice] Apache/2.2.22 (Debian) mod_python/3.3.1 Python/2.7.3 configured -- resuming normal operations

I hope someone can help me.
Best

**Comment by xorader** [comment]
Solution: https://stackoverflow.com/questions/23719304/error-on-apache2-restart-using-mod-python-undefined-symbol-sincos/
