### ISSUE TITLE
Fallback content handler blocked by mod_python

### ISSUE THREAD

**Issue by avylove** [grisha/mod_python#65]
I'm working with an application, Foreman, which serves ruby-generated content using passenger. Working on handling some input similar to the way the intercept_form_submit_module Apache module works.

If I don't specify anything, passenger handles the content.

If I specify a location, I can do preprocessing and the content is still generated by passenger. this works fine with intercept_form_submit_module and mod_perl. The handler in this case just returns an OK.

```
<Location /users/login>
  PerlFixupHandler myApache::myModule
</Location>
```
If I do this with mod_python, I get a 404 Not Found error.

```
<Location /users/login>
  PythonFixupHandler my_apache.my_module
</Location>
```

It seems like something in mod_python prevents the processing from continuing.

Interestingly, when I enable the rewrite engine, it works as expected.

```
<Location /users/login>
  PythonFixupHandler my_apache.my_module
  RewriteEngine on
</Location>
```

Is there something going on behind the scenes that requires the rewrite engine or is it just fixing something in the configuration?

**Comment by grisha** [comment]
Off the top of my head I'm not sure what is going on, but one theory is that mod_python still expects there to be a `PythonHandler`. I say this from looking at the test: https://github.com/grisha/mod_python/blob/master/test/htdocs/tests.py#L924  (and I don't know why the above three lines assign `mod_python` then `None` then `mod_python` again - I suspect it's a typo). But it does set a `PythonHandler`, and perhaps without one, a `404` is proper response? Just a theory. If you figure it out, please do share! :)
