### ISSUE TITLE
undefined symbol: mp_version_component

### ISSUE THREAD

**Issue by tek0011** [grisha/mod_python#67]
Thanks for your suggestion yesterday on getting mod_python to compile/install.   Hoping there might be some insight on this new issue.   I am not sure why I am having so many issues, Ive set up mod_python half a dozen times in the past without issue.   This time, not so much.  

After yum reinstalling httpd-devel and python-devel dependencies, mod_python installed, but now I can not get apache to start; displaying the following error:

```
[*NEXT* root@puppet 1 /etc/httpd/conf.modules.d]# systemctl status httpd -l
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-01-04 12:09:09 CST; 1s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 25987 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 25985 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=1/FAILURE)
 Main PID: 25985 (code=exited, status=1/FAILURE)

Jan 04 12:09:09 puppet httpd[25985]: [Thu Jan 04 12:09:09.046522 2018] [so:warn] [pid 25985] AH01574: module ssl_module is already loaded, skipping
Jan 04 12:09:09 puppet httpd[25985]: [Thu Jan 04 12:09:09.046543 2018] [so:warn] [pid 25985] AH01574: module systemd_module is already loaded, skipping
Jan 04 12:09:09 puppet httpd[25985]: [Thu Jan 04 12:09:09.046594 2018] [so:warn] [pid 25985] AH01574: module cgi_module is already loaded, skipping
Jan 04 12:09:09 puppet httpd[25985]: httpd: Syntax error on line 41 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/01-mod_python.conf: Cannot load modules/mod_python.so into server: /etc/httpd/modules/mod_python.so: undefined symbol: mp_version_component
Jan 04 12:09:09 puppet systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Jan 04 12:09:09 puppet kill[25987]: kill: cannot find process ""
Jan 04 12:09:09 puppet systemd[1]: httpd.service: control process exited, code=exited status=1
Jan 04 12:09:09 puppet systemd[1]: Failed to start The Apache HTTP Server.
Jan 04 12:09:09 puppet systemd[1]: Unit httpd.service entered failed state.
```

No other log file shows much of anything.   Dr. Google doesn't really get me anywhere and I didnt find this error in any previous issues on here.  

httpd.conf
```
[*NEXT* root@puppet 130 /var/log/httpd]# cat /etc/httpd/conf/httpd.conf
# Security
ServerTokens OS
ServerSignature On
TraceEnable On

ServerName "puppet.lab.beer.town"
ServerRoot "/etc/httpd"
PidFile run/httpd.pid
Timeout 120
KeepAlive Off
MaxKeepAliveRequests 100
KeepAliveTimeout 15
LimitRequestFieldSize 8190


User apache
Group apache

AccessFileName .htaccess
<FilesMatch "^\.ht">
    Order allow,deny
    Deny from all
    Satisfy all
</FilesMatch>

<Directory />
  Options Indexes FollowSymLinks
  AllowOverride All
</Directory>

HostnameLookups Off
ErrorLog "/var/log/httpd/error_log"
LogLevel debug
EnableSendfile On

#Listen 80

#LoadModule python_module modules/mod_python.so

Include "/etc/httpd/conf.modules.d/*.load"
Include "/etc/httpd/conf.modules.d/*.conf"
Include "/etc/httpd/conf/ports.conf"

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\"" forwarded

IncludeOptional "/etc/httpd/conf.d/*.conf"
```

01-mod_python.conf
```
[*NEXT* root@puppet 0 /var/log/httpd]# cat /etc/httpd/conf.modules.d/01-mod_python.conf
LoadModule python_module modules/mod_python.so
```

Not really sure what else to put in here, thats about all the logs and info I can find.   Any help would really be appreciated, been fighting this thing for a few days. 

Thanks.

**Comment by tek0011** [comment]
Alright, magic must be on my side.  I was able to get it to compile after making all the changes here:
https://github.com/grisha/mod_python/issues/20#issuecomment-30947818
Then deleting version.c so it would repopulate from the other includes.

I know the project isnt active, but sure would be nice to have these changes.   
Must not have too much magic on my side yet though, since now I am running into:

```
[Fri Jan 05 08:21:09.016421 2018] [:error] [pid 21275] [client 100.91.160.19:54497] PythonHandler mod_python.psp: Traceback (most recent call last):
[Fri Jan 05 08:21:09.016433 2018] [:error] [pid 21275] [client 100.91.160.19:54497] PythonHandler mod_python.psp:   File "/usr/lib64/python2.7/site-packages/mod_python/apache.py", line 398, in HandlerDispatch\n    result = obj(req)
[Fri Jan 05 08:21:09.016437 2018] [:error] [pid 21275] [client 100.91.160.19:54497] PythonHandler mod_python.psp:   File "/usr/lib64/python2.7/site-packages/mod_python/psp.py", line 351, in handler\n    p.run()
[Fri Jan 05 08:21:09.016440 2018] [:error] [pid 21275] [client 100.91.160.19:54497] PythonHandler mod_python.psp:   File "/usr/lib64/python2.7/site-packages/mod_python/psp.py", line 271, in run\n    raise et(ev).with_traceback(etb)
[Fri Jan 05 08:21:09.016442 2018] [:error] [pid 21275] [client 100.91.160.19:54497] PythonHandler mod_python.psp: AttributeError: 'exceptions.ImportError' object has no attribute 'with_traceback'
```

Which is where I was at on Tuesday.  Come full circle :)  Any idea what this errors means?  I fought it for quite some time a few days ago.   Eventually gave up, but looks like I need to get past it.

**Comment by grisha** [comment]
How are you getting the code that you're compiling? There is a note on the [website](http://www.modpython.org):
<blockquote>
Mod_python is going to be maintained on Github from here on. There is no plan for additional releases, the latest code is the master branch, which will be kept as stable as possible. 
</blockquote>

The above is meant to imply that the code should be obtained via `git clone https://github.com/grisha/mod_python` from here on. You'll get the master branch which already has the above fix.

<p/>
Regarding the second question - it's probably just an import error because it mentions `exceptions.ImportError` which in turn means that whatever it is you're trying to run isn't found in PythonPath. You should double-check your configuration and the URL you're hitting, etc.

**Comment by tek0011** [comment]
Huh.  I suppose that could be a big issue..  I was just doing what I've done in the past:

http://dist.modpython.org/dist/

Eyes naturally go immediately to the download.  

Let me try to recompile from latest master branch.  Perhaps that will fix the second issue as well.

**Comment by grisha** [comment]
I removed those links from the website, hopefully it's a little clearer now.

**Comment by tek0011** [comment]
Thats all it was :)  The new master version ended up fixing both issues.  I just looked at the site and I think that is a huge improvement.  Immediately my eyes look for a download, when I dont see it, time to start reading everywhere.   The site wasnt the only confusion really.    On various how-to's they say go to modpython.org and download the latest, so you click on the link and naturally just move on to download.

Thats my fault for not stopping to read first!  Sorry.    

Anyhow, thanks for your help.  Using the latest master and recompiling fixed both the original compiler issues and python import issues.
