### ISSUE TITLE
3.5.0-462d30a - make_obcallback: could not import mod_python.apache

### ISSUE THREAD

**Issue by estrand2020** [grisha/mod_python#69]
When loading the mpinfo test page (and all other pages served by mod_python) I am encountering the following error in my Apache error.log file:

[Tue Mar 13 00:58:15.446436 2018] [:error] [pid 10283] make_obcallback: could not import mod_python.apache.\n
ImportError: No module named mod_python.apache
[Tue Mar 13 00:58:15.446479 2018] [:error] [pid 10283] make_obcallback: Python path being used "['/usr/lib64/python27.zip', '/usr/lib64/python2.7/', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload']".
[Tue Mar 13 00:58:15.446484 2018] [:error] [pid 10283] get_interpreter: no interpreter callback found.

The Python path is missing the directory where mod_python is installed (/usr/lib64/python2.7/site-packages) so it looks like site.py file is not being loaded prior to the import attempt.  The page loads fine so the error is not a show stopper - somewhere before the error the module must be loaded successfully.

mod_python version: 3.5.0-462d30a
OS: CentOS Linux release 7.4 (AWS ami-b63ae0ce - us-west-2)
Python version:  2.7.5  (stock with OS)
Apache version: 2.4.6 (stock with OS - prefork)

I can eliminate the error by adding a symbolic link in /usr/lib64/python2.7:

ln -s ./site-packages/mod_python mod_python

or adding PYTHONPATH to /etc/sysconfig/httpd:

PYTHONPATH=/usr/lib64/python2.7/site-packages

Neither approach seems ideal.  Is there a better way to prevent this error?

I have also duplicated the error with CentOS 6.9 / Apache 2.2.15 / Python 2.6.6.

If helpful, the error is not generated when I tried mod_python version 3.4.1-f311fae.

**Comment by grisha** [comment]
It's kind of strange that `site-packages` is not in the path by default, that's traditionally the place where separately installed packages go... My CentOs 7 has it:

```
$ /usr/bin/python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/home/grisha/.local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
>>> 
```
I suspect your `sys.path` is somehow affected by your environment, but off the top of my head I don't have any ideas. A clue is that it happened for both CentOS 6.9 and 7.4, is there anything in common between these installs?

**Comment by estrand2020** [comment]
I have near-identical output from the command line:

```
$ /usr/bin/python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
>>>

```
If I modify the mptest.py example to output sys.path this is output:

`['/var/www/html/test/', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']`

Both CentOS installs start are similar.  While not verbatim, these are steps:

1. - Start with stock AWS CentOS AMI
2. - yum update
3. - yum install httpd-devel python-devel gcc git
4. - git clone https://github.com/grisha/mod_python.git
5. - cd mod_python
6. - ./configure
7. - make
8. - make install
9. - configure Apache to load mod_python.so

I'll try a different distro next.

**Comment by estrand2020** [comment]
It turns out I'm bringing up something that has been encountered before.  Looking at the thread for issue #46 (PyEval_SaveThread: NULL tstate), it is mentioned first by @adaugherity [on May 24, 2016](https://github.com/grisha/mod_python/issues/46#issuecomment-221431403).  According to pull #68, the underlying problem disappears with Python 2.7.14, which I have confirmed.
