### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by sandrotosi** [grisha/mod_python#91]
looking at https://github.com/grisha/mod_python/releases/tag/release-3-3-1 it says "1097 commits to master since this tag" -- maybe it's time to cut a new release?

it looks like master also supports python3, which almost all linux distributions are moving towards (while dropping py2), so having such a release would help with that effort.

Regards,
Sandro

**Comment by grisha** [comment]
The last/latest release was 3.3.5 (with Python 3 support), not 3.3.1.  But as it says on http://modpython.org/ - what's in github master _is_ the "latest release" for the foreseeable future.

**Comment by sandrotosi** [comment]
but there are no tags on github after 3.3.1.. maybe you could push those?
