### ISSUE TITLE
Regarding Releasing mod_python

### ISSUE THREAD

**Issue by rohan-97** [grisha/mod_python#92]
Hi @grisha ,

I was trying to find a better forum to ask this question but on GitHub I think we can ask question only by raising Issue.

I  am using mod_python in my project and I am currently compiling it from scratch by cloning this repository.

I would really be helpful if we have a separate release of mod_python.
I would like to know that are you planning to release mod_python from master branch in future.

Thanks.

**Comment by grisha** [comment]
Since the development is frozen and we're only fixing bugs, we haven't done an official release in years - compiling it from master is fine and that's the latest greatest version.
